frase='Curso em Vídeo Python'
dividido=frase.split()
print(dividido)
print(dividido[0])
print(dividido[1])
print(dividido[2])
print(dividido[3])
print(dividido[0][1])
print(dividido[0][2])
print(dividido[0][3])
print(dividido[0][4])
